In [4]:
from bidr_relight.bidr_process import rotation_matrix_from_vectors
import numpy as np

%load_ext autoreload
%autoreload 2

v1 = np.array((1.0, 0.5, 0.2))
v1_norm = np.linalg.norm(v1)
v1 = v1 / v1_norm
v2 = np.array((-0.5, 0.2, 0.3))
v2_norm = np.linalg.norm(v2)
v2 = v2 / v2_norm

# Test 1. Full rotation from v1 to v2.
R = rotation_matrix_from_vectors(v1, v2, rot_angle=None)
result = R @ v1
expected_result = v2
print(result - expected_result)
assert (result - expected_result).max() < 1e-7

# Test 2. Partial rotation from v1 to v2, using a simpler example.
v1 = np.array((1.0, 0.0, 0.0))
v2 = np.array((0.0, 1.0, 0.0))
theta = np.deg2rad(45)
R = rotation_matrix_from_vectors(v1, v2, rot_angle=theta)
result = R @ v1
expected_result = np.array((np.cos(theta), np.sin(theta), 0.0))
print(result - expected_result)
assert (result - expected_result).max() < 1e-7

# Test 3. Use percentage to indicate amount of degrees
v1 = np.array((1.0, 0.0, 0.0))
v2 = np.array((0.0, 1.0, 0.0))
R = rotation_matrix_from_vectors(v1, v2, rot_percent=100.0)
result = R @ v1
expected_result = v2
print(result - expected_result)
assert (result - expected_result).max() < 1e-7

R = rotation_matrix_from_vectors(v1, v2, rot_percent=50.0)
result = R @ v1
expected_result = np.array((np.cos(theta), np.sin(theta), 0.0))
print(result - expected_result)
assert (result - expected_result).max() < 1e-7


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
[1.11022302e-16 5.55111512e-17 0.00000000e+00]
[0. 0. 0.]
[1.11022302e-16 0.00000000e+00 0.00000000e+00]
[0. 0. 0.]
